<a href="https://colab.research.google.com/github/sachinn1586/ARRAY-AND-FUNCTION-/blob/main/(NN_Module)creating_a_model_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn



In [4]:
class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)#this line say num_features area input and 1 is output model name is linear
    self.sigmoid = nn.Sigmoid()#activation function

  def forward(self,features):
    #z = wx1+b
    out = self.linear(features)

    out = self.sigmoid(out)



    return out

In [5]:
features =torch.rand(10,5)
model = Model(features.shape[1])
model(features)



tensor([[0.3233],
        [0.3109],
        [0.3558],
        [0.3614],
        [0.3573],
        [0.3519],
        [0.3691],
        [0.3383],
        [0.3547],
        [0.3139]], grad_fn=<SigmoidBackward0>)

In [6]:
model.linear.weight

Parameter containing:
tensor([[-0.0597, -0.2024, -0.3236,  0.0947, -0.0865]], requires_grad=True)

In [7]:
model.linear.bias

Parameter containing:
tensor([-0.4186], requires_grad=True)

In [8]:
!pip install torchinfo

In [9]:
from torchinfo import summary


In [10]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [20]:
class new_Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features,3)#this line say num_features area input and 1 is output model name is linear
    self.relu1 = nn.ReLU()
    self.linear2 = nn.Linear(3,1) # Modified to accept 1 input feature
    self.sigmoid1 = nn.Sigmoid()#activation function

  def forward(self,features):
    #z = wx1+b
    out = self.linear1(features)
    out = self.relu1(out)
    out = self.linear2(out)
    out = self.sigmoid1(out)

    return out


features =torch.rand(10,5)
model = new_Model(features.shape[1])
model(features)


tensor([[0.6166],
        [0.6176],
        [0.6189],
        [0.6166],
        [0.6175],
        [0.6173],
        [0.6166],
        [0.6166],
        [0.6181],
        [0.6209]], grad_fn=<SigmoidBackward0>)

In [21]:
model.linear2.weight

Parameter containing:
tensor([[0.0730, 0.3127, 0.0558]], requires_grad=True)

In [22]:
model.linear2.bias

Parameter containing:
tensor([0.4752], requires_grad=True)

In [23]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
new_Model                                [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [24]:
#creating a sequential container for making and inproving the code
class new_Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),#this line say num_features area input and 1 is output model name is linear
        nn.ReLU(),
        nn.Linear(3,1), # Modified to accept 1 input feature
        nn.Sigmoid()#activation function

    )

  def forward(self,features):
    out = self.network(features)

    return out


features =torch.rand(10,5)
model = new_Model(features.shape[1])
model(features)



tensor([[0.4800],
        [0.4888],
        [0.4801],
        [0.4732],
        [0.4660],
        [0.4969],
        [0.4749],
        [0.5108],
        [0.4980],
        [0.4769]], grad_fn=<SigmoidBackward0>)

In [25]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [27]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [28]:
df.shape

(569, 33)

In [31]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [32]:
df.shape

(569, 31)

In [55]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [56]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [57]:
X_test_scaled

array([[ 1.2181472 , -0.40338931,  1.1849693 , ...,  0.76060257,
        -0.62398224,  0.55686341],
       [-0.72280984,  2.36738671, -0.71893854, ..., -0.71353611,
        -0.04597685, -0.64695332],
       [-0.4059189 , -0.59642553, -0.40565282, ..., -0.5314322 ,
         0.24302584,  0.0764188 ],
       ...,
       [ 1.39073959,  1.66115663,  1.50481598, ...,  1.02849097,
        -0.93153055,  0.42593144],
       [-0.10883363, -0.81064866, -0.08088543, ...,  0.33920509,
        -0.50189019,  1.01945366],
       [-0.51626485, -0.16327108, -0.54917377, ..., -0.47168406,
         0.10702457, -0.66588976]])

In [58]:
X_train_scaled

array([[-0.97179558, -1.00368488, -0.9899881 , ..., -1.22854404,
        -0.94853071, -0.89096291],
       [ 1.4756211 ,  1.00436265,  1.50481598, ...,  0.61160847,
         0.00966003, -0.43378307],
       [-0.90954915, -0.47872052, -0.84769733, ...,  0.59806355,
        -0.57761817,  0.603934  ],
       ...,
       [-0.73129799,  1.23741858, -0.74518237, ..., -1.0175443 ,
         0.51039197, -0.9039479 ],
       [-0.50494732, -0.36572371, -0.44829905, ..., -0.6330191 ,
        -0.55289066,  0.51033387],
       [-0.95764867, -2.24194162, -0.96907505, ..., -1.04945011,
        -1.27307919, -0.38779457]])

In [59]:
y_train

144    B
244    M
440    B
541    B
53     M
      ..
258    M
441    M
305    B
431    B
166    B
Name: diagnosis, Length: 455, dtype: object

In [60]:
y_test

498    M
456    B
519    B
455    B
354    B
      ..
105    M
443    B
83     M
73     M
107    B
Name: diagnosis, Length: 114, dtype: object

In [62]:
#Labeling
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [63]:
y_train,y_test

(array([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
        0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
        1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 

In [64]:
X_train_tensor = torch.from_numpy(X_train_scaled.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test_scaled.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [72]:
X_train_tensor.shape


torch.Size([455, 30])

In [71]:
y_train_tensor.shape


torch.Size([455])

In [73]:

import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [76]:
learning_rate = 0.1
epochs = 25
#define a loss function
loss_function = nn.BCELoss()

In [77]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6759659647941589
Epoch: 2, Loss: 0.5132277011871338
Epoch: 3, Loss: 0.42697983980178833
Epoch: 4, Loss: 0.37434178590774536
Epoch: 5, Loss: 0.33828005194664
Epoch: 6, Loss: 0.3116946816444397
Epoch: 7, Loss: 0.291094571352005
Epoch: 8, Loss: 0.2745438516139984
Epoch: 9, Loss: 0.2608751654624939
Epoch: 10, Loss: 0.24933961033821106
Epoch: 11, Loss: 0.23943327367305756
Epoch: 12, Loss: 0.23080356419086456
Epoch: 13, Loss: 0.22319605946540833
Epoch: 14, Loss: 0.2164219170808792
Epoch: 15, Loss: 0.21033795177936554
Epoch: 16, Loss: 0.2048332393169403
Epoch: 17, Loss: 0.19982051849365234
Epoch: 18, Loss: 0.19523000717163086
Epoch: 19, Loss: 0.19100511074066162
Epoch: 20, Loss: 0.18709947168827057
Epoch: 21, Loss: 0.1834745705127716
Epoch: 22, Loss: 0.1800982505083084
Epoch: 23, Loss: 0.17694322764873505
Epoch: 24, Loss: 0.17398634552955627
Epoch: 25, Loss: 0.17120768129825592


In [78]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5997229814529419
